### ISSUE TITLE
Error on drag/drop into hp fields

### ISSUE THREAD

**Issue by eryon** [MeAndUnique/ConstitutionalAmendments#1]
This has not always been the case, but since the last update or two, this error has started popping up.

I often use the modifier box to fix rolls, such as when a player forgot to upcast and adds a normal die or when some modifier was forgotten, using a negative number to heal or positive number to deal damage.  In previous versions of CA (and without CA at all), I could just put this number in the lower-left modifier box and drag it onto the wounds or current hp field of the target (either their sheet or on the CT), and it would report a chat message of dealing damage or healing and take effect as expected.  Now, however, it seems that any drop onto the field is treated as a "set" instead of "adjust by" and I get a console error:
```
[ERROR]  Script execution error: [string "utility/scripts/dynamic_hp.lua"]:45: attempt to call field 'getActorFromCT' (a nil value)
```

This occurs when I have only CA v2.1.1 loaded with no other extensions. Attached is a mkv if you want to see it in action.

[issue.zip](https://github.com/MeAndUnique/ConstitutionalAmendments/files/7809265/issue.zip)

**Comment by MeAndUnique** [comment]
Should be working again in v2.1.2. Sorry for the inconvenience. And thanks for providing so thorough information!

**Comment by eryon** [comment]
Yes, this is working perfectly now. Thanks!
